### ISSUE TITLE
Change Login Page UI

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#1]
The default login page of spring security does not have proper alignment. Please update the login page (html page) to look nicer.

**Comment by jalilhaidari2** [comment]
Dear @hpardess, as the best of my knowledge, we can not customize the login page currently we have as a dependency, we can make a configuration file with @Configuration and @EnableWebSecurity annotations in it, in that case, we have to have jsp sort of things... for the login page. Please correct me if I am wrong.

**Comment by jalilhaidari2** [comment]
BW, the dependency will remain as it is, so all functionality will remain the same.

**Comment by hpardess** [comment]
Please read following post and you will get some information : https://www.devglan.com/spring-security/spring-boot-security-hibernate-login-example

**Comment by jalilhaidari2** [comment]
Dear @hpardess, in the example you shared the link of, they have used jsp, which is not actually a template engine, and has to be compiled to servlet first, on the other hand, Thymeleaf is a template engine which takes the HTML file, parses it and then produces web content which is being served. In addition, as you know, Thymeleaf has some more advantages over jsp, so,  I have no idea which one to use, the decision is to be taken by you. :)

**Comment by hpardess** [comment]
I recommend use jsp page for login.

**Comment by jalilhaidari2** [comment]
Dear @hpardess, I would very much appreciate your response to the following:
   1. The pull request i have created for the Issue #1
   2. To avoid conflicts in the code and waste of time, i request you to assign a specific issue to specific 
       person.
