### ISSUE TITLE
Recommendations by Noor Jafar

### ISSUE THREAD

**Issue by jalilhaidari2** [nsia-infosys/ASIMS#116]
1. Form Instances:
  a). validation (i.e: If anyone enters more or less than 10  digits in the phone number field, the 
        system should give an error and avoid further processing.
  b). A clear hint should be displayed for each field.
  c) Begin-repeat: One should be able to submit multiple records at once.

**Comment by hpardess** [comment]
I add the hint for each field. The hint is displayed as tooltip. Please contact jafar to create a form with multiple language hint.
