### ISSUE TITLE
User Mangement - Backend

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#12]
Please write a controller for User Management to have following routes:
-    GET - /users - Read list of Users -/users OR /users?size=20&page=5
-    POST - /users - Create new User - /users
-    GET - /users/ - Read specific User - /users/123
-    PUT - /users/ - Update specific User - /users/123
-    DELETE - /users/ - Delete specific User - /users/123

Please write test case for each controller and service function.

**Comment by zafarshafaq** [comment]
@msn1992  I will do it
