### ISSUE TITLE
Role Management - Backend

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#13]
Please write a controller for Role Management to have following routes:

    GET - /roles - Read list of Roles -/roles OR /roles?size=20&page=5
    POST - /roles - Create new Role - /roles 
    GET - /roles/ - Read specific Role - /roles/123
    PUT - /roles/ - Update specific Role - /roles/123
    DELETE - /roles/ - Delete specific Role - /roles/123

Please write test case for each controller and service function.

**Comment by jalilhaidari2** [comment]
merged
