### ISSUE TITLE
Sending Errors through email 

### ISSUE THREAD

**Issue by mohbadar** [nsia-infosys/ASIMS#139]
System should send an email to predefined email-addresses when an error is happened.

**Comment by mohbadar** [comment]
Sending errors with SMTP Appender in Log4j2. 

SMTPAppender

Sends an e-mail when a specific logging event occurs, typically on errors or fatal errors.
The number of logging events delivered in this e-mail depend on the value of BufferSize option. The SMTPAppender keeps only the last BufferSize logging events in its cyclic buffer. This keeps memory requirements at a reasonable level while still delivering useful application context. All events in the buffer are included in the email. The buffer will contain the most recent events of level TRACE to WARN preceding the event that triggered the email.

The default behavior is to trigger sending an email whenever an ERROR or higher severity event is logged and to format it as HTML. The circumstances on when the email is sent can be controlled by setting one or more filters on the Appender. As with other Appenders, the formatting can be controlled by specifying a Layout for the Appender.

**Comment by mohbadar** [comment]
Following Appender in Log4j2.xml is sending email to specified address in case any error is happened. 

       <SMTP name="MailAppender"
             subject="Log"
             to="asmis.admin@nsia.gov.af"
             from="nsia.asmis.log@nsia.gov.af"
             smtpHost="yourSMTPHost"
             smtpPort="587"
             smtpUsername="yourSMTPUsername"
             smtpPassword="yourSMTPPassword"
             bufferSize="1">
           <ThresholdFilter level="ERROR" onMatch="ACCEPT" onMismatch="DENY"/>
           <PatternLayout>
               <Pattern>${LOG_PATTERN}</Pattern>
           </PatternLayout>
       </SMTP>

**Comment by hpardess** [comment]
Currently, we are using SLF4J in our application. I recommend that remove the given dependency form pom.xml file and replace our application logging with Log4j2.

**Comment by mohbadar** [comment]
It has been done
