### ISSUE TITLE
ODK Briefcase Integration 

### ISSUE THREAD

**Issue by mohbadar** [nsia-infosys/ASIMS#151]
ODK Briefcase is a desktop application that runs on macOS, Windows, and Linux. It is used for pulling, pushing, and exporting forms on ODK servers such as ASIMS. You can also use Briefcase to pull forms directly from ODK Collect. It also can export data into CSV and JSON format.

**Comment by hpardess** [comment]
@mohbadar : Do we have any progress about this feature?
