### ISSUE TITLE
Workflow Transition History

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#155]
All workflow steps transitions have to logged in database for history purpose.

**Comment by mohbadar** [comment]
I have managed the instance transition by adding a new model with the follow definition: 

@Data
@Getter
@Setter
@ToString
@EqualsAndHashCode
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "instance_transition")
public class InstanceTransition {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "instance_transition_generator")
	@SequenceGenerator(name="instance_transition_generator", sequenceName = "instance_transition_seq", allocationSize = 1)
	@Column(unique = true, updatable = false, nullable = false)
	private Long id;

    @ManyToOne(targetEntity = User.class, fetch = FetchType.LAZY)
    @JoinColumn(nullable = true, name = "user_id")
    private User user;

    @ManyToOne(targetEntity = Instance.class, fetch = FetchType.LAZY)
    @JoinColumn(nullable = true, name = "instance_id")
    private Instance instance;

    @Column(name = "previous_step", insertable = true, updatable = false)
    private String previousStep;
    @Column(name = "next_step", insertable = true, updatable = false)
    private String nextStep;

    @Column(name = "description", insertable = true, updatable = false)
    @Type(type = "text")
    private String description;


    public InstanceTransition(User user, Instance instance, String previousStep, String nextStep, String description)
    {
        this.user= user;
        this.instance=instance;
        this.previousStep=previousStep;
        this.nextStep=nextStep;
        this.description=description;
    }
}
