### ISSUE TITLE
ODK-X Integration

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#159]
We need to integrate odk-x with ASIMS. The data will be received as JSON. The received data will be transformed and stored as XML in our database.
Their routes should start with /odkx/

**Comment by MirwaisAkrami** [comment]
Link to the sync endpoint rest protocol, it can give a good insight about the request and response structure of ODK-X APIs

[(https://github.com/opendatakit/opendatakit/wiki/ODK-2.0-Synchronization-API-(RESTful))](url)

**Comment by hpardess** [comment]
@sediqamousavi why the route start with /odkx/odktables? the controller should be only /odkx
or all routes start /odkx/odktables including authentication
