### ISSUE TITLE
Elasticsearch/Solr Integration for Visualization and Read Operations

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#160]
Reading Blogs:
https://stackoverflow.com/a/49298814
https://dzone.com/articles/elasticsearch-vs-solr-have-both-with-spring-data-a
https://www.quora.com/How-can-I-use-elastic-search-with-MySql-in-Spring-Boot-application

**Comment by mohbadar** [comment]
It is decided to use Change Data Capture (CDC) mechanism with Kafka to integrate Postgres with Elastic in real-time. CDC allows us to select the fields, tables, views, trigers, procedures or entire data-store that need to be audited, and then capture database inserts, updates, and deletions automatically to make a record available of what changed, where, and when, in simple relational tables. These “change” tables contain the metadata necessary to understand the changes in the right context, ultimately driving better  decisions. 

Background Information

In this platform, we are using Apache Kafka stack as main technologies, especially KafkaConnect and Kafka Stream API. 

Kafka Connect, an open source component of Kafka, is a framework for connecting Kafka with external systems such as databases, key-value stores, search indexes, and file systems. Using Kafka Connect you can use existing connector implementations for common data sources and sinks to move data into and out of Kafka.

Source Connector
    A source connector ingests entire databases and streams table updates to Kafka topics. It can also collect metrics from all of your application servers into Kafka topics, making the data available for stream processing with low latency.

Sink Connector
    A sink connector delivers data from Kafka topics into secondary indexes such as Elasticsearch or batch systems such as Hadoop for offline analysis.


Kafka Connect is focused on streaming data to and from Kafka, making it simpler for you to write high quality, reliable, and high performance connector plugins. It also enables the framework to make guarantees that are difficult to achieve using other frameworks. Kafka Connect is an integral component of an ETL pipeline when combined with Kafka and a stream processing framework.

Kafka Connect can run either as a standalone process for running jobs on a single machine (e.g., log collection), or as a distributed, scalable, fault tolerant service supporting an entire organization. This allows it to scale down to development, testing, and small production deployments with a low barrier to entry and low operational overhead, and to scale up to support a large organization's data pipeline.

The main benefits of using Kafka Connect are:

    •     Data Centric Pipeline -- use meaningful data abstractions to pull or push data to Kafka.
    •     Flexibility and Scalability -- run with streaming and batch-oriented systems on a single node or scaled to an organization-wide service.
    •     Reusability and Extensibility -- leverage existing connectors or extend them to tailor to your needs and lower time to production.

Kafka Connect is designed to have the following key properties:

    • Broad copying by default -- Quickly define connectors that copy vast quantities of data between systems to keep configuration overhead to a minimum. The default unit of work should be an entire database, even if it is also possible to define connectors that copy individual tables.
    • Streaming and batch -- Support copying to and from both streaming and batch-oriented systems.
    • Scales to the application -- Scale down to a single process running one connector in development, testing or a small production environment, and scale up to an organization-wide service for copying data between a wide variety of large scale systems.
    • Focus on copying data only -- Focus on reliable, scalable data copying; leave transformation, enrichment, and other modifications of the data up to frameworks that focus solely on that functionality. Correspondingly, data copied by Kafka Connect must integrate well with stream processing frameworks.
    • Parallel -- Parallelism should be included in the core abstractions, providing a clear avenue for the framework to provide automatic scalability.
    • Accessible connector API -- It must be easy to develop new connectors. The API and runtime model for implementing new connectors should make it simple to use the best library for the job and quickly get data flowing between systems. Where the framework requires support from the connector, e.g. for recovering from faults, all the tools required should be included in the Kafka Connect APIs.

Typical Challenges that we can address

    • Liveliness
    • Volume & Velocity
    • Data/system lifespan
    • Changing business requirements


Typical parts of a data pipeline

    • Data ingestion
    • Filtering & Enrichment
    • Routing
    • Processing
    • Querying / Visualization / Reporting
    • Data warehousing
    • Reprocessing capabilities

Typical requirements

    • Scalability
        ◦ Billions of messages and terabytes of data 24/7
    • Availability and redundancy
        ◦ Across physical locations
    • Latency
        ◦ Real-time / batch
    • Adaptability / Platform support


Kafka Connect Elasticsearch Connector

The Elasticsearch connector allows moving data from Apache Kafka® to Elasticsearch. It writes data from a topic in Kafka to an index in Elasticsearch and all data for a topic have the same type.

Elasticsearch is often used for text queries, analytics and as an key-value store (use cases). The connector covers both the analytics and key-value store use cases. For the analytics use case, each message is in Kafka is treated as an event and the connector uses topic+partition+offset as a unique identifier for events, which then converted to unique documents in Elasticsearch. For the key-value store use case, it supports using keys from Kafka messages as document IDs in Elasticsearch and provides configurations ensuring that updates to a key are written to Elasticsearch in order. For both use cases, Elasticsearch's idempotent write semantics guarantees exactly once delivery.

Mapping is the process of defining how a document, and the fields it contains, are stored and indexed. Users can explicitly define mappings for types in indices. When mapping is not explicitly defined, Elasticsearch can determine field names and types from data, however, some types such as timestamp and decimal, may not be correctly inferred. To ensure that the types are correctly inferred, the connector provides a feature to infer mapping from the schemas of Kafka messages.


Features
The Elasticsearch connector offers a bunch of features:

Exactly Once Delivery: The connector relies on Elasticsearch's idempotent write semantics to ensure exactly once delivery to Elasticsearch. By setting IDs in Elasticsearch documents, the connector can ensure exactly once delivery. If keys are included in Kafka messages, these keys are translated to Elasticsearch document IDs automatically. When the keys are not included, or are explicitly ignored, the connector will use topic+partition+offset as the key, ensuring each message in Kafka has exactly one document corresponding to it in Elasticsearch.

Mapping Inference: The connector can infer mappings from the Connect schemas. When enabled, the connector creates mappings based on schemas of Kafka messages. However, the inference is limited to field types and default values when a field is missing. If more customizations are needed (e.g. user defined analyzers), we highly recommend to manually create mappings.

Schema Evolution: The connector supports schema evolution and can handle backward, forward and fully compatible changes of schemas in Connect. It can also handle some incompatible schema changes such as changing a field from integer to string.

**Comment by mohbadar** [comment]
Elasticsearch integration is done. You can browse the API.

Sample: 
Request:

- Method: GET

- URL: http://localhost:8090/api/elastic/instances 

Response: 

{
"content": [
{
"id": 27,
"title": null,
"active": false,
"envSlug": "nsia",
"version": null,
"content": {
"content": {
"sample_form": {
"xmlns:odk": "http://www.opendatakit.org/xforms",
"game": "",
"education": "",
"xmlns:jr": "http://openrosa.org/javarosa",
"gender": "",
"studied": "",
"photo": "",
"parcentage": "",
"geopoints": "",
"xmlns:ev": "http://www.w3.org/2001/xml-events",
"xmlns:orx": "http://openrosa.org/xforms",
"xmlns:xsd": "http://www.w3.org/2001/XMLSchema",
"audio_record": "",
"meta": {
"instanceID": ""
},
"name": "",
"video_recored": "",
"xmlns:h": "http://www.w3.org/1999/xhtml",
"id": "Sample_Form",
"other_game": "",
"begin": {
"photo": "",
"jr:template": ""
},
"begin0": {
"times": "",
"date_time": "",
"starting": ""
},
"age": "",
"some-file": ""
}
}
},
"instanceSubmission": null,
"currentStep": null,
"ownerId": 2,
"formId": 3
}
],
"pageable": {
"sort": {
"sorted": false,
"unsorted": true,
"empty": true
},
"pageSize": 1,
"pageNumber": 0,
"offset": 0,
"paged": true,
"unpaged": false
},
"facets": [],
"aggregations": null,
"scrollId": null,
"maxScore": 1,
"totalElements": 1,
"totalPages": 1,
"last": true,
"first": true,
"sort": {
"sorted": false,
"unsorted": true,
"empty": true
},
"numberOfElements": 1,
"size": 1,
"number": 0,
"empty": false
}

**Comment by mohbadar** [comment]
Integration with elasticsearch is done
