### ISSUE TITLE
ASIMS v1.2 hotfixes

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#192]
- Fix horizontal Scrollbar in all pages. By @MirwaisAkrami 
- Fix vertical scroll bar of Instance View/Edit. Scroll should appear to only instance child views, not main view. By @MirwaisAkrami 
- Fix Excel Export. It should be downloadable. By @ahmadfaiaz 
- Hide Administration Menu. By @jalilhaidari2 
- Ability to delete a user by admin if he/she does not have any activity in ASIMS. By @jalilhaidari2 
- Fix the popup message on instance save and create. By @jalilhaidari2 
- The instance form should open on create new instance. By @jalilhaidari2 
- Set preferences like color, sidebar, table row display count, preferred Lang. By @jalilhaidari2 
- Add spinner/loader to login page. Talk with Akrami about this. By @jalilhaidari2 
- User details have to be saved in InMemoryDB after login. @hpardess 
- If environment is not set, the logged in user have to be forwarded back to preference page. By @hpardess 
- User, Form and Instance Count in Dashboard should be based on Environment and status. All active forms, users and instance have to be considered in count. By @hpardess 
- Active column in /forms table. By @hpardess

**Comment by MirwaisAkrami** [comment]
Horizontal scroll issue is fixed and pushed to master branch.

**Comment by hpardess** [comment]
I add the active column in /forms table to identify the deactivated/achieved forms in the list.

**Comment by hpardess** [comment]
User, Form and Instance Count in Dashboard is now filtered by envSlug and active flug.

**Comment by hpardess** [comment]
Excel Export is fixed by @ahmadfaiaz 
Excel Import Template is also fixed
