### ISSUE TITLE
User Management - Frontend

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#2]
Develop a users management module. Consider following activities,
- Create user table in PostgreSQL
- Connect the database through hibernate
- Create user modal
- Write a test case for user controller to handle CRUD operations
- Create user controller to handle CRUD operations
- Design UI in Angular7 with using angular material

**Comment by hpardess** [comment]
- GET - /users - Read list of Users -/users OR /users?size=20&page=5
- POST - /users - Create new User - /users
- GET - /users/<userid> - Read specific User - /users/123
- PUT - /users/<userid> - Update specific User - /users/123
- DELETE - /users/<userid> - Delete specific User - /users/123

![popular status codes](https://user-images.githubusercontent.com/6196491/51161781-68521a80-18b1-11e9-9e55-0c3e21575c85.PNG)
![methods used in rest api and response](https://user-images.githubusercontent.com/6196491/51161913-e31b3580-18b1-11e9-965b-136e7c46d145.PNG)

**Comment by msn1992** [comment]
@hpardess  I finished  UI for user management using angular material. but how can i get data from database?
