### ISSUE TITLE
Forms and Instance List/Grid View Switcher

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#218]
Add a new sidebar item as Forms Folder. only 10 forms similar like table should be displayed as grid view or list view based on top corner switcher. This will five feeling of folder structure view for some users.
Also be a button to load more and append more forms as folder items to view.
You can take advise of Mr. Jafar too.

Also bellow link is sample to be considered
https://www.codehim.com/demo/bootstrap-list-grid-view-switcher/
https://codepen.io/webdevstudios/pen/WrgGmN
https://www.jqueryscript.net/demo/List-View-Grid-View-Switcher-Plugin-jQuery-simple-list-grid/

**Comment by zafarshafaq** [comment]
@hpardess  I think this issue have been completed. I want to close it.

**Comment by hpardess** [comment]
@zafarshafaq , I have fixed the folder alignment and size.
- Also fixed the reloading issue of page when we click on folder
- fixed the two click on List/Grid buttons
- now clicking instance folder will open the readonly view of instance
