### ISSUE TITLE
Lazy load the relationships in Hibernate

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#28]
The relationships objects in model should be loaded lazy for better database performance.
for now we used `@ManyToMany(fetch=FetchType.EAGER)`
If we have thousands records due to relation then fetching all records during initialization of parent object is unnecessary and causes to affect the database performance.

We have to use `@ManyToMany(fetch=FetchType.LAZY)` and load the relation records only when we need it.

**Comment by jalilhaidari2** [comment]
I'm removing the issues that are complete, just to reduce the mass. :)
