### ISSUE TITLE
org.hibernate.QueryException: could not instantiate class [com.nsia.model.Instance] from tuple

### ISSUE THREAD

**Issue by jalilhaidari2** [nsia-infosys/ASIMS#289]
Trying to list the instances of a form throws Exception the Exception message is: 
`org.hibernate.QueryException: could not instantiate class [com.nsia.model.Instance] from tuple`.

**Comment by hpardess** [comment]
Make sure you have "is_first_update" column in instance table and all rows are either true or false value. The row with null value in this column will throw such exception.
This field was added by @sediqamousavi
