### ISSUE TITLE
Role Management - Frontend

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#3]
Develop a roles management module. Consider following activities,
- Create role and privilege table in PostgreSQL
- Connect the database through hibernate
- Create role modal and privilege modal
- Write a test case for role controller to handle CRUD operations
- Create role controller to handle CRUD operations
- Design UI in Angular7 with using angular material

**Comment by msn1992** [comment]
@jalilhaidari2  please solve the following problems.

1. My account. the following buttons not working.
           a. change Picture.
           b. delete picture.
2. Forms--> Instance 
          a. after pressing the save button a message is displaying with content, hide the console message 
             and make a success alert.
3. User Management: the following button not working.
          a. add button.
          b. refresh button.
          c. edit button.
4. Role Management:
           a. in view role states always showing as deactive even if it is active.
5. Group Management:
           a. in view role states always showing as deactive even if it is active.
           b. cant edit states, it is always deactive.
6. Form Management: 
          a. created date and updated date is not taken automatically in the time of form creation and 
            updating.
7. dataSource: the following buttons not working
          a. add button.
          b. view button.
          c. connect button.
8. consider the following also.
         a. if a user is deactive, it shouldn't log in to the system.
         b. Instance Comment every comment should have an edit button and a delete button.
