### ISSUE TITLE
Map Overlay rendering and GeoServer Integration with ASIMS

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#309]
- Setup the Geoserver in Tomcat. 
- Each layer config as JSON should be stored in system registry.
- Add a field to System Registry as Type drop-down. there should be one option as map layer.
- Each layer config have to saved with type "map layer"
- Add a drop-down in form management to list all saved layers of specific environment.
- A user should be able to select multiple layers for a form.
- Selected layers will be ploted on top of instance map of that form instances.
- Also selected layer will be displayed in Form Map for user to select.

- The layer data will be rendered based on config we saved in system registry entry as JSON and through cURL it will be fetched from GeoServer or any remote server.

**Comment by hpardess** [comment]
@sediqamousavi : Which above steps are completed till now?

**Comment by sediqamousavi** [comment]
@hpardess  5 above steps are completed and we're working on the remaining steps.
