### ISSUE TITLE
Design Home Page

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#31]
For sample refer to attached image for simple home page design.
<img width="1261" alt="screen shot 1397-06-20 at 1 22 20 am" src="https://user-images.githubusercontent.com/6196491/52520154-fe484d80-2c83-11e9-8f6e-c7034450bc27.png">

**Comment by ahmadfaiaz** [comment]
@hpardess sir,
I have created the dashboard, the source code is under test-branch. you can merge the branch now.

**Comment by hpardess** [comment]
The code is merged.
