### ISSUE TITLE
Redirect back to first URL if Login required

### ISSUE THREAD

**Issue by MirwaisAkrami** [nsia-infosys/ASIMS#316]
If for example [http://asims.gov.af/more/instances/1024/edit](http://asims.gov.af/more/instances/1024/edit) is clicked, it should first check if the user is logged in and if not then redirect to login page. 
After successful login, the permissions should be checked if the user was privileged then he/she should be redirected back to the above URL, otherwise to not found page.

**Comment by jalilhaidari2** [comment]
The first part is now working, I will check the permissions part.
