### ISSUE TITLE
View/Edit Logged In User Profile

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#32]
Implement the logged in user profile:
- A user should be able to view his profile
- A user should be able to edit his profile
- A user should be able to upload his photo or change his photo

**Comment by msn1992** [comment]
@hpardess  at user profile, change button should get the path and store it in database . but file chooser cant get path .
as well as delete button should delete the path from database . please solve this problem for me. 
thanks .

**Comment by hpardess** [comment]
@msn1992 : Please remember following points:
- Do not commit unnecessary test data to repository. Better keep it locally for your testing purpose.
- Please remove the unnecessary code while you committing your code. Better have a quick look and remove the dead code.
- Please avoid unnecessary white spaces like 5 or 6 enters between lines.
- always refer to angular material components before adding your own css.

**Comment by msn1992** [comment]
@hpardess  when i commit the code there was no error but now there is an error on  onSubmit()  method at upload profile   html file please check it.
And I will avoid other unnecessary code or white space .
thanks for remind.
