### ISSUE TITLE
List uploaded forms in ODK Collect

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#34]
https://forum.opendatakit.org/t/odk-survey-blank-forms-list-response/15131?u=hpardess

Please visit the above link and here the response template is clearly explained.

You can refer to ODK Aggregate source code and get idea how it is implemented. https://github.com/opendatakit/aggregate

**Comment by zafarshafaq** [comment]
@hpardess  I have visit your shared link. On coming Saturday I will create a controller to handle it.

**Comment by hpardess** [comment]
@zafarshafaq & @msn1992 : you can use Android Studio and setup the emulator to test odk collect against your localhost.
https://developer.android.com/studio/run/emulator#networkaddresses
https://developer.android.com/studio/run/emulator-networking.html

**Comment by hpardess** [comment]
https://bitbucket.org/javarosa/javarosa/wiki/FormListAPI?rev=f02ddae1088d
