### ISSUE TITLE
Report from instance using Jasper report 

### ISSUE THREAD

**Issue by sediqamousavi** [nsia-infosys/ASIMS#349]
# Steps to get a report :
1- install iReport Designer 5.6:
- Download iReport 5.6.0
- Extract iReport 5.6.0 and install it
- open file ireport.conf inside folder etc
- add jdk home in file ireport.conf (jdkhome="C:\Program Files\Java\jre7") only support using jre 7
- run iReport 5.6.0
for more information refer to the following link: [https://www.youtube.com/watch?v=kl0YxzFuz_0](url)

2- get XML source from ASIMS and fill the form
3- for creating a report from XML file in iReport Designer refer to the following links: [https://community.jaspersoft.com/wiki/build-reports-based-xml-datasource-using-ireport-designer](url) , [https://www.youtube.com/watch?v=LG8fZC3H3Us](url)
4- click on the XML tab of iReport designer and copy XML lines code and then paste to the text area of create report modal in ASIMS
5- Assign report to a form and then check it in instances of a form 

# notes:
- To fix ClassNotFoundException org.apache.xpath.CachedXPathAPI, I downloaded the xalan binaries, serializer and copied it to "C:\Program Files (x86)\Jaspersoft\iReport-5.6.0\ireport\libs"
xalan-j2-2.7.0
serializer-2.7.0
- Be sure to choose the xpath : for more information refer to the following link:
 [https://www.youtube.com/watch?v=LG8fZC3H3Us](url)
- You will have to set the language value in your template to Java. There is a way you can do this:
 select the root object in your Report Inspector (the one with the same name as your report). Then in the Properties window, select Java from the Languages drop-down.

**Comment by sediqamousavi** [comment]
@hpardess please check the top guide If you have points that are not mentioned above, please let me know

**Comment by hpardess** [comment]
@sediqamousavi : refer to this http://thegeekyasian.com/add-custom-fonts-to-jasper-report-in-java-project-jaspersoft/
