### ISSUE TITLE
Comment during workflow transitioning

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#415]
There should comment box in transition popup. so a user can also add comment and transition in same time. If comment is blank then do not add entry in comment table and skip it... else transition and comments will be saved in same time.

**Comment by mohbadar** [comment]
should the comment  be saved in instance_comment table?

**Comment by hpardess** [comment]
Yeah... The comment should save in instance_comment but in UI there should be text box Bellow transitions list ...
It will give user to add comment if required during transitioning.

Like while closing with resolution as Reject, the user will add comment too.

Also add a property in workflow to identify the comment be required for certain resolution or steps ... CommentRequired: true

**Comment by mohbadar** [comment]
It is resolved

**Comment by asr-era** [comment]
it is done

**Comment by mohbadar** [comment]
it is done.
