### ISSUE TITLE
Datasource Management - Frontend & Backend

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#44]
Create a data-source management to register the different DBMS data sources in ASIMS.

- Add New Datasource: A list of database type should be shown and only one option should be selected. (MySQL, PostgreSQL, MongoDB, Microsoft SQL Server, GoogleSpreadsheet ...)
also get relevent details about datasource like: Name, Host, Port, User, Password, SSL Mode, Database Name). 

You can refer to redash and know how it is implemented.

**Comment by msn1992** [comment]
I am receiving below warning and error when running  ng g c admin/data-source Management  to create the component

Two or more projects are using identical roots. Unable to determine project using current working directory. Using default workspace project instead.
More than one module matches. Use skip-import option to skip importing the component into the closest module.

**Comment by msn1992** [comment]
@hpardess  I solve the above error and complete the task number #44.
