### ISSUE TITLE
ASIMS ER Diagram

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#48]
Design an ER Diagram that covers whole ASIMS db structure. Please design draw.io and keep the xml file with your self for future change or we may commit it in ASIMS project for future changes.

Also it is better to upload the image of ERD to this issue.

**Comment by ahmadfaiaz** [comment]
![asims erd](https://user-images.githubusercontent.com/27572987/53875349-f3ce6900-4021-11e9-9890-326265e545e6.png)

**Comment by hpardess** [comment]
@ahmadfaiaz Please update ERD and add new models.
Following new models are added (instance, instance_history, instance_watcher, instance_transition, instance_comment, instance_assignee_history)

**Comment by ahmadfaiaz** [comment]
@hpardess sir,
I have created new models in draw.io but couldn't set the relationship between them due to not existance of foreign keys and column name in the new models
