### ISSUE TITLE
vendor.js:48039 ERROR TypeError: Cannot read property 'instance' of null

### ISSUE THREAD

**Issue by jalilhaidari2** [nsia-infosys/ASIMS#505]
Steps to reproduce:
 1-Login to your user
 2-From list of forms, select work-plan-realization form to list all instances
 3-Click view an instance

Note: This problem is only with some forms, it works with other forms. Work statistics form 11 as an example.

**Comment by hpardess** [comment]
There is a new feature introduced that when a form is created or updated, the Xform is automatically parsed and a list of columns with their properties is created and saved in database.

Currently we have old forms that does not have theses properties. therefore, you need to just edit and save those forms and it will work fine without any exception.
