### ISSUE TITLE
Workflow Management

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#58]
Investigate and find how the workflow is implemented in other data collection applications. 
Here is one approach to have JSON for each workflow. Here is the sample:

`{
   "id":"xyz",
   "name":"XYZ Workflow",
   "imageUrl": "https://asims.af/resources/images/xyzWorkflow.png",
   "steps":[
      {
         "name":"Open",
         "transitions":[
            {
               "name":"Assign ODK Inspection",
               "toStep":"ODK Inspection Assigned"
            }
         ]
      },
      {
         "name":"ODK Inspection Assigned",
         "transitions":[
            {
               "name":"Reject",
               "toStep":"Rejected"
            },
            {
               "name":"Start ODK Inspection",
               "toStep":"ODK Inspection Started"
            }
         ]
      },
      {
         "name":"ODK Inspection Started",
         "transitions":[
            {
               "name":"Reject",
               "toStep":"Rejected"
            },
            {
               "name":"Finish ODK Inspection",
               "toStep":"ODK Inspection Finished"
            }
         ]
      },
      {
         "name":"ODK Inspection Finished",
         "transitions":[
            {
               "name":"Start GIS Verification",
               "toStep":"GIS Verification Started"
            }
         ]
      },
      {
         "name":"GIS Verification Started",
         "transitions":[
            {
               "name":"Reject",
               "toStep":"Rejected"
            },
            {
               "name":"Approve by GIS",
               "toStep":"GIS Verification Finished"
            }
         ]
      },
      {
         "name":"GIS Verification Finished",
         "transitions":[
            {
               "name":"Start Report Processing",
               "toStep":"Report Processing Started"
            }
         ]
      },
      {
         "name":"Report Processing Started",
         "transitions":[
            {
               "name":"Reject",
               "toStep":"Rejected"
            },
            {
               "name":"Finish Report Processing",
               "toStep":"Report Processing Finished"
            }
         ]
      },
      {
         "name":"Report Processing Finished",
         "transitions":[
            {
               "name":"Reject",
               "toStep":"Rejected"
            },
            {
               "name":"Approve by Eng Manager",
               "toStep":"Report Approved (Eng Manager)"
            }
         ]
      },
      {
         "name":"Report Approved (Eng Manager)",
         "transitions":[
            {
               "name":"Reject",
               "toStep":"Rejected"
            },
            {
               "name":"Approve by Eng TL",
               "toStep":"Report Approved (Eng TL)"
            }
         ]
      },
      {
         "name":"Report Approved (Eng TL)",
         "transitions":[
            {
               "name":"Reject",
               "toStep":"Rejected"
            },
            {
               "name":"Approve by QC",
               "toStep":"Report Approved (QC)"
            }
         ]
      },
      {
         "name":"Report Approved (QC)",
         "transitions":[
            {
               "name":"Reject",
               "toStep":"Rejected"
            },
            {
               "name":"Approve by Mon Tl",
               "toStep":"Report Approved (Mon TL)"
            }
         ]
      },
      {
         "name":"Report Approved (Mon TL)",
         "transitions":[
            {
               "name":"Reject",
               "toStep":"Rejected"
            },
            {
               "name":"Close",
               "toStep":"Closed",
               "resolutions":[
                  "Fixed",
                  "Won't Fix",
                  "Duplicate",
                  "Incomplete",
                  "Cannot Reproduce"
               ]
            }
         ]
      },
      {
         "name":"Closed",
         "transitions":[
            {
               "name":"Reopen",
               "toStep":"Reopened"
            }
         ]
      },
      {
         "name":"Reopened",
         "transitions":[
            {
               "name":"Reassign to GIS",
               "toStep":"ODK Inspection Finished"
            },
            {
               "name":"Reassign to Report Writers",
               "toStep":"GIS Verification Finished"
            },
              {
               "name":"Approve tl",
               "toStep":"Report Approved (Mon TL)"
            },
            {
               "name":"Close",
               "toStep":"Closed",
               "resolutions":[
                  "Fixed",
                  "Won't Fix",
                  "Duplicate",
                  "Incomplete",
                  "Cannot Reproduce"
               ]
            }
         ]
      },
      {
         "name":"Rejected",
         "transitions":[
            {
               "name":"Reassign to Engineer",
               "toStep":"ODK Inspection Assigned"
            },
            {
               "name":"Reassign to GIS",
               "toStep":"ODK Inspection Finished"
            },
            {
               "name":"Reassign to Report Writers",
               "toStep":"GIS Verification Finished"
            },
            {
               "name":"Close",
               "toStep":"Closed",
               "resolutions":[
                  "Fixed",
                  "Won't Fix",
                  "Duplicate",
                  "Incomplete",
                  "Cannot Reproduce"
               ]
            }
         ]
      }
   ]
}`

**Comment by jalilhaidari2** [comment]
Here is how the workflow is implemented in erpNext.
![1](https://user-images.githubusercontent.com/33908181/58617299-041a7b00-82d5-11e9-9c21-fd81aa52a6c8.png)
As we can see, we have some workflow related options.


![2](https://user-images.githubusercontent.com/33908181/58617417-4cd23400-82d5-11e9-9e52-2ede2a40587c.png)
Clicking on workflow will list all the created workflows.


![4](https://user-images.githubusercontent.com/33908181/58617575-b9e5c980-82d5-11e9-86c3-5c6888c848b6.png)

In a workflow we have "Document State " and "Transition". The important thing here is that "state","action" and "action master" are all separate tables.



![workflow tables](https://user-images.githubusercontent.com/33908181/58618253-607e9a00-82d7-11e9-9a3b-9a74622023c5.png)
List of tables related to workflow and the description of the workflow table itself.

**Comment by mohbadar** [comment]
There are multiple solutions available to manage the flow of information. In below, I have highlighted a list of possible solutions for workflow management:
1. Dexecutor: https://github.com/dexecutor
2. Spring container, in this case, we can consider each process as a bean and ask the ApplicationContext to manage dependencies between beans for us.
3. Apache Camel, consider each process as a channel that only users with specific permission can access it.
4. OSWF: http://oswf.sourceforge.net/
5. Activiti: https://www.activiti.org/. Activiti is an open-source workflow engine written in Java that can execute business processes described in BPMN. In this solution the process management is based on BPMN standards, 
6. Our own implementation.

**Comment by mohbadar** [comment]
Based on our discussion, we have decided to have our own implementation for workflow management. In this scenario, we need to have following functionalities: 
1. Register each process, each process has a action_name, status and a unique identifier
2. Map a set processes to a Group. A Group might have many processes and Many process might belong to Many Groups
3. Create a workflow of a set of process. A Workflow might have many processes and a Process might belong to Many Workflows.
4. Map workflow to a Form. A Form can have only one Workflow. 
5. Track the current process of each Instance of Form by an attribute in Instance class.

**Comment by mohbadar** [comment]
This is how workflow is designed with Activity and Workflow class in user's Group level: 

@Data
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@ToString
@EqualsAndHashCode
@Entity(name = "Activity")
@Table(name = "activity")
public class Activity implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "activity_generator")
    @SequenceGenerator(name = "activity_generator", sequenceName = "activity_seq", allocationSize = 1)
    @Column(unique = true, updatable = false, nullable = false)
    private Long id;

    @Column(
            name = "action",
            unique = true,
            nullable = false,
            insertable = true,
            length = 64,
            updatable = true)
    private String action;
    @Column(
            name = "status",
            unique = true,
            nullable = false,
            insertable = true,
            length = 1,
            updatable = true)
    private Boolean status;

}

@Data
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@ToString
@EqualsAndHashCode
@Entity(name = "Group")
@Table(name = "group_tbl")
public class Group {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "group_tbl_generator")
    @SequenceGenerator(name = "group_tbl_generator", sequenceName = "group_tbl_seq", allocationSize = 1)
    @Column(unique = true, updatable = false, nullable = false)
    private Long id;

    @Column(name = "name")
    private String name;

    @Column
    private String description;

    @Column(name = "active", length = 1, nullable = false)
    private boolean active;

    @Column(name = "env_id")
    private String envId;

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "group_role",
            joinColumns = @JoinColumn(name = "group_id", referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(name = "role_id", referencedColumnName = "id"))
    @JsonIgnore
    private Collection<Role> roles;
}

@Data
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@ToString
@EqualsAndHashCode
@Entity(name = "Form")
@Table(name = "form")
public class Form {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "form_generator")
    @SequenceGenerator(name = "form_generator", sequenceName = "form_seq", allocationSize = 1)
    @Column(unique = true, updatable = false, nullable = false)
    private Long id;

    @Column(name = "xml_form_id")
    private String xmlFormId;

    @Column(name = "name")
    private String name;

    @Column(name = "description")
    private String description;

    @Column(name = "active")
    private boolean active;

    @Column(name = "show_on_map")
    private boolean showOnMap;

    @Column(name = "xml_content")
    @Type(type = "text")
    private String xmlContent;

    @Column(name = "env_id")
    private String envId;

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "form_group",
            joinColumns = @JoinColumn(name = "form_id", referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(name = "group_id", referencedColumnName = "id"))
    @JsonIgnore
    private Collection<Group> groups;

    // This field is not mapped to database
    @Transient
    private Long instanceCount;

    @Column(name = "created_at")
    @CreationTimestamp
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    @UpdateTimestamp
    private LocalDateTime updatedAt;

    @OneToMany(mappedBy = "form", fetch = FetchType.LAZY)
    @JsonIgnore
    private Collection<Instance> instances;

    @OneToOne(
            targetEntity = Workflow.class,
            fetch = FetchType.EAGER
    )
    @JoinColumn(
            nullable = true,
            name = "workflow_id"
    )
    private Workflow workflow;
}

@Data
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@ToString
@EqualsAndHashCode
@Entity(name = "Workflow")
@Table(name = "workflow")
public class Workflow implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "workflow_generator")
    @SequenceGenerator(name = "workflow_generator", sequenceName = "workflow_seq", allocationSize = 1)
    @Column(unique = true, updatable = false, nullable = false)
    private Long id;

    @Column(
            name = "name",
            unique = true,
            nullable = false,
            insertable = true,
            length = 64,
            updatable = true)
    private String name;

    @Column(
            name = "description",
            unique = true,
            nullable = false,
            insertable = true,
            length = 512,
            updatable = true)
    @Type(type = "text")
    private String description;

    @ManyToMany
    @JoinTable(
            name = "workflows_activities",
            joinColumns = @JoinColumn(
                    name = "workflow_id",
                    referencedColumnName = "id"
            ),
            inverseJoinColumns = @JoinColumn(
                    name = "activity_id",
                    referencedColumnName = "id"
            )
    )
    private Collection<Activity> activities = new HashSet<>();

}
