### ISSUE TITLE
Display map view in Instance View

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#71]
Display a small OpenStreet map above the question of type GeoPointQuestion.
Also below the map show the geopoint in text field. If someone update the text field, the marker in map should change too.

**Comment by hpardess** [comment]
@msn1992 : Remove the $event parameter from updateMarker() function.
Here is the line of code to get the latest change of input field: this.form.controls[this.question.key].value

**Comment by msn1992** [comment]
Thanks, sir I got it.

**Comment by hpardess** [comment]
This task was partially implemented.

**Comment by hpardess** [comment]
@msn1992 This please commit the instance map relevant code under this task.
