### ISSUE TITLE
Implement Digest Auth for /odk/** routes

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#82]
The new versions of ODK collect does not use the Basic Auth, but instead they use Digest Auth.
I have done partially which is committed to Digest Auth branch. 

I found the issue that digest auth require password in plain text while we store the password in bcrypt encoding. Refer to following blog:
http://www.kenansevindik.com/feature-interaction-problems-and-spring-security/

Also I have created an issue to spring security repository (https://github.com/spring-projects/spring-security/issues/6759)

**Comment by hpardess** [comment]
Digest Authentication require password in plain text format while we store the user password in bcrypt encoding. The bcrypt encoding can not be revert back to plain text. Therefore, to implement Digest Auth for ODK we will maintain a new filed in user table to hold the plain text password for ODK collect.

**Comment by nealeu** [comment]
Hi,
I see you've raised an issue on Spring Security.  The storage of end user's plain text passwords should never be done.  As soon as a hacker gets access to your database, all of those passwords can be used by the hacker to access other sites, as demonstrated by this having been done in the past on various sites.
