### ISSUE TITLE
Add/remove watcher to watchers list of Instance

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/ASIMS#87]
There should be a watchers list in instance edit page. We should be able to add new watcher or remove previous watcher.

The watchers have to receive an email on each edit/change in instance for notification.

**Comment by hpardess** [comment]
@div100 : Please share your progress about this task.

**Comment by div100** [comment]
Mr. @hpardess i will share everything as soon as possible, my PC has damaged and resolving of the issues waste the time, thanks.
